create table if not exists public.service_requests (
    id bigint generated by default as identity primary key,
    requester_name text not null,
    department text not null,
    category text not null,
    description text not null,
    priority text not null,
    status text not null default 'Pending',
    user_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.service_requests enable row level security;

drop policy if exists "Authenticated users can view service requests"
    on public.service_requests;
create policy "Authenticated users can view service requests"
    on public.service_requests for select
    to authenticated
    using (true);

drop policy if exists "Authenticated users can create their own service requests"
    on public.service_requests;
create policy "Authenticated users can create their own service requests"
    on public.service_requests for insert
    to authenticated
    with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own service requests"
    on public.service_requests;
create policy "Users can update their own service requests"
    on public.service_requests for update
    to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own service requests"
    on public.service_requests;
create policy "Users can delete their own service requests"
    on public.service_requests for delete
    to authenticated
    using ((select auth.uid()) = user_id);

create or replace function public.set_service_requests_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_service_requests_updated_at
    on public.service_requests;
create trigger set_service_requests_updated_at
    before update on public.service_requests
    for each row execute function public.set_service_requests_updated_at();